services:
  db:
    image: postgres:16
    container_name: toby_tours_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # UWAGA: na produkcji nie wystawiamy bazy na internet
    ports: []
    volumes:
      - tobys_tours_pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ./app
    container_name: toby_tours_app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - tobys_tours_media:/app/media

volumes:
  tobys_tours_pgdata:
  tobys_tours_media:

